### ISSUE TITLE
Its not a google extension...

### ISSUE THREAD

**Issue by Nalin-2005** [Shaunak0806/Qouter-google-extension#1]
I think you made this as an extension for Google Chrome. So this project should be renamed to **Quoter-chrome-extension**, because there are no extensions for Google, and this extension can also be used on Microsoft Edge.

**Comment by Nalin-2005** [comment]
Nice project btw. 👌

**Comment by Shaunak0806** [comment]
> I think you made this as an extension for Google Chrome. So this project should be renamed to **Quoter-chrome-extension**, because there are no extensions for Google, and this extension can also be used on Microsoft Edge.

Thanks a lot for the correction. 😇

**Comment by Shaunak0806** [comment]
> Nice project btw. 👌

Thank you so much 😇✌🏻
